---
title: "Owen cumulative functions"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Owen cumulative functions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## The Owen distribution

Let $Z \sim {\cal N}(0,1)$ and $X \sim \chi^2_\nu$ be two independent random variables.
For real numbers $\delta_1$ and $\delta_2$, define the two random variables
$$
T_1 = \frac{Z+\delta_1}{\sqrt{\dfrac{X}{\nu}}}
\quad \text{and} \quad\;
T_2 = \frac{Z+\delta_2}{\sqrt{\dfrac{X}{\nu}}}.
$$

Both $T_1$ and $T_2$ follow a non-central Student distribution. 
The number of degrees of freedom is $\nu$ for each of them, and their respective non-centrality parameters are $\delta_1$ and $\delta_2$ respectively. 

Owen (1965) studied the distribution of the pair $(T_1, T_2)$.

The four Owen cumulative functions are
$$
\begin{align}
Q_1(\nu, t_1, t_2, \delta_1, \delta_2) & = \Pr(T_1 \leq t_1, T_2 \leq t_2), \\
Q_2(\nu, t_1, t_2, \delta_1, \delta_2) & = \Pr(T_1 \leq t_1, T_2 \geq t_2), \\
Q_3(\nu, t_1, t_2, \delta_1, \delta_2) & = \Pr(T_1 \geq t_1, T_2 \geq t_2), \\
Q_4(\nu, t_1, t_2, \delta_1, \delta_2) & = \Pr(T_1 \geq t_1, T_2 \leq t_2).
\end{align}
$$

Owen provided a way to evaluate these functions *when $\nu$ is an integer number*. Owen's algorithms are implemented in the `OwenQ` package. 

For $\delta_1 > \delta_2$, these four functions are implemented in the `OwenQ` package under the names `powen1`, `powen2`, `powen3` and `powen4`. 
For general values of $\delta_1$ and $\delta_2$, they are implemented under the names `psbt1`, `psbt2`, `psbt3` and `psbt4` 


## Application to equivalence testing 
