// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// RcppOwenT
double RcppOwenT(double h, double a);
RcppExport SEXP OwenQ_RcppOwenT(SEXP hSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOwenT(h, a));
    return rcpp_result_gen;
END_RCPP
}
// RcppOwenStudent
NumericVector RcppOwenStudent(double q, int nu, NumericVector delta);
RcppExport SEXP OwenQ_RcppOwenStudent(SEXP qSEXP, SEXP nuSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOwenStudent(q, nu, delta));
    return rcpp_result_gen;
END_RCPP
}
// RcppOwenQ1
NumericVector RcppOwenQ1(int nu, double t, NumericVector delta, NumericVector R);
RcppExport SEXP OwenQ_RcppOwenQ1(SEXP nuSEXP, SEXP tSEXP, SEXP deltaSEXP, SEXP RSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type R(RSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOwenQ1(nu, t, delta, R));
    return rcpp_result_gen;
END_RCPP
}
// RcppOwenQ2
NumericVector RcppOwenQ2(int nu, double t, NumericVector delta, NumericVector R);
RcppExport SEXP OwenQ_RcppOwenQ2(SEXP nuSEXP, SEXP tSEXP, SEXP deltaSEXP, SEXP RSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type R(RSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOwenQ2(nu, t, delta, R));
    return rcpp_result_gen;
END_RCPP
}
// RcppOwenCDF4
NumericVector RcppOwenCDF4(int nu, double t1, double t2, NumericVector delta1, NumericVector delta2);
RcppExport SEXP OwenQ_RcppOwenCDF4(SEXP nuSEXP, SEXP t1SEXP, SEXP t2SEXP, SEXP delta1SEXP, SEXP delta2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< double >::type t2(t2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type delta1(delta1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type delta2(delta2SEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOwenCDF4(nu, t1, t2, delta1, delta2));
    return rcpp_result_gen;
END_RCPP
}
// RcppOwenCDF3
NumericVector RcppOwenCDF3(int nu, double t1, double t2, NumericVector delta1, NumericVector delta2);
RcppExport SEXP OwenQ_RcppOwenCDF3(SEXP nuSEXP, SEXP t1SEXP, SEXP t2SEXP, SEXP delta1SEXP, SEXP delta2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< double >::type t2(t2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type delta1(delta1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type delta2(delta2SEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOwenCDF3(nu, t1, t2, delta1, delta2));
    return rcpp_result_gen;
END_RCPP
}
// RcppOwenCDF2
NumericVector RcppOwenCDF2(int nu, double t1, double t2, NumericVector delta1, NumericVector delta2);
RcppExport SEXP OwenQ_RcppOwenCDF2(SEXP nuSEXP, SEXP t1SEXP, SEXP t2SEXP, SEXP delta1SEXP, SEXP delta2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< double >::type t2(t2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type delta1(delta1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type delta2(delta2SEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOwenCDF2(nu, t1, t2, delta1, delta2));
    return rcpp_result_gen;
END_RCPP
}
// RcppOwenCDF1
NumericVector RcppOwenCDF1(int nu, double t1, double t2, NumericVector delta1, NumericVector delta2);
RcppExport SEXP OwenQ_RcppOwenCDF1(SEXP nuSEXP, SEXP t1SEXP, SEXP t2SEXP, SEXP delta1SEXP, SEXP delta2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< double >::type t2(t2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type delta1(delta1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type delta2(delta2SEXP);
    rcpp_result_gen = Rcpp::wrap(RcppOwenCDF1(nu, t1, t2, delta1, delta2));
    return rcpp_result_gen;
END_RCPP
}
// RcppSpecialOwenCDF2
NumericVector RcppSpecialOwenCDF2(int nu, double t, NumericVector delta);
RcppExport SEXP OwenQ_RcppSpecialOwenCDF2(SEXP nuSEXP, SEXP tSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppSpecialOwenCDF2(nu, t, delta));
    return rcpp_result_gen;
END_RCPP
}
