# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RcppOwenT <- function(h, a) {
    .Call('OwenQ_RcppOwenT', PACKAGE = 'OwenQ', h, a)
}

RcppOwenStudent <- function(q, nu, delta) {
    .Call('OwenQ_RcppOwenStudent', PACKAGE = 'OwenQ', q, nu, delta)
}

RcppOwenQ1 <- function(nu, t, delta, R) {
    .Call('OwenQ_RcppOwenQ1', PACKAGE = 'OwenQ', nu, t, delta, R)
}

RcppOwenQ2 <- function(nu, t, delta, R) {
    .Call('OwenQ_RcppOwenQ2', PACKAGE = 'OwenQ', nu, t, delta, R)
}

RcppOwenCDF4 <- function(nu, t1, t2, delta1, delta2) {
    .Call('OwenQ_RcppOwenCDF4', PACKAGE = 'OwenQ', nu, t1, t2, delta1, delta2)
}

RcppOwenCDF3 <- function(nu, t1, t2, delta1, delta2) {
    .Call('OwenQ_RcppOwenCDF3', PACKAGE = 'OwenQ', nu, t1, t2, delta1, delta2)
}

RcppOwenCDF2 <- function(nu, t1, t2, delta1, delta2) {
    .Call('OwenQ_RcppOwenCDF2', PACKAGE = 'OwenQ', nu, t1, t2, delta1, delta2)
}

RcppOwenCDF1 <- function(nu, t1, t2, delta1, delta2) {
    .Call('OwenQ_RcppOwenCDF1', PACKAGE = 'OwenQ', nu, t1, t2, delta1, delta2)
}

