# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RcppOwenT01 <- function(h, a, jmax = 50L, cutpoint = 8) {
    .Call('OwenQ_RcppOwenT01', PACKAGE = 'OwenQ', h, a, jmax, cutpoint)
}

RcppOwenT <- function(h, a, jmax = 50L, cutpoint = 8) {
    .Call('OwenQ_RcppOwenT', PACKAGE = 'OwenQ', h, a, jmax, cutpoint)
}

RcppOwenStudent <- function(q, nu, delta, jmax = 50L, cutpoint = 8) {
    .Call('OwenQ_RcppOwenStudent', PACKAGE = 'OwenQ', q, nu, delta, jmax, cutpoint)
}

RcppOwenQ1 <- function(nu, t, delta, R, jmax = 50L, cutpoint = 8) {
    .Call('OwenQ_RcppOwenQ1', PACKAGE = 'OwenQ', nu, t, delta, R, jmax, cutpoint)
}

RcppOwenQ2 <- function(nu, t, delta, R, jmax = 50L, cutpoint = 8) {
    .Call('OwenQ_RcppOwenQ2', PACKAGE = 'OwenQ', nu, t, delta, R, jmax, cutpoint)
}

RcppOwenCDF4 <- function(nu, t1, t2, delta1, delta2, jmax = 50L, cutpoint = 8) {
    .Call('OwenQ_RcppOwenCDF4', PACKAGE = 'OwenQ', nu, t1, t2, delta1, delta2, jmax, cutpoint)
}

RcppOwenCDF3 <- function(nu, t1, t2, delta1, delta2, jmax = 50L, cutpoint = 8) {
    .Call('OwenQ_RcppOwenCDF3', PACKAGE = 'OwenQ', nu, t1, t2, delta1, delta2, jmax, cutpoint)
}

RcppOwenCDF2 <- function(nu, t1, t2, delta1, delta2, jmax = 50L, cutpoint = 8) {
    .Call('OwenQ_RcppOwenCDF2', PACKAGE = 'OwenQ', nu, t1, t2, delta1, delta2, jmax, cutpoint)
}

RcppOwenCDF1 <- function(nu, t1, t2, delta1, delta2, jmax = 50L, cutpoint = 8) {
    .Call('OwenQ_RcppOwenCDF1', PACKAGE = 'OwenQ', nu, t1, t2, delta1, delta2, jmax, cutpoint)
}

