# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RcppOwenT01 <- function(h, a, jmax, cutpoint) {
    .Call('OwenQ_RcppOwenT01', PACKAGE = 'OwenQ', h, a, jmax, cutpoint)
}

RcppOwenT <- function(h, a, jmax, cutpoint) {
    .Call('OwenQ_RcppOwenT', PACKAGE = 'OwenQ', h, a, jmax, cutpoint)
}

RcppOwenQ1 <- function(nu, t, delta, R, jmax, cutpoint) {
    .Call('OwenQ_RcppOwenQ1', PACKAGE = 'OwenQ', nu, t, delta, R, jmax, cutpoint)
}

